on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs-test:
    steps:
      - run: apt-get install neovim
      - uses: actions/checkout@v4
      - run: nvim --headless --noplugin -V1 -es -c "helptags doc"

  luacheck:
    steps:
      - run: apt-get install lua-check
      - uses: actions/checkout@v4
      - run: luacheck .

  stylua:
    steps:
      - run: apt-get install stylua
      - uses: actions/checkout@v4
      - run: stylua --check .

  test:
    commands:
      - run: apt-get install neovim
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        repository: https://github.com/nvim-lua/plenary.nvim
        path: ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
      - uses: actions/checkout@v4
        repository: https://github.com/nvim-treesitter/nvim-treesitter
        path: ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter
      - run: ln -s "$(pwd)" ~/.local/share/nvim/site/pack/vendor/start
      - run: scripts/test
