on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs-test:
    container:
      image: alpine
    steps:
      - uses: actions/checkout@v4
      - run: apk add neovim
      - run: nvim --headless --noplugin -V1 -es -c "helptags doc"

  luacheck:
    container:
      image: pipelinecomponents/luacheck
    steps:
      - uses: actions/checkout@v4
      - run: luacheck .

  stylua:
    container:
      image: fnichol/stylua
    steps:
      - uses: actions/checkout@v4
      - run: stylua --check .

  test:
    container:
      image: archlinux
    commands:
      - uses: actions/checkout@v4
      - run: pacman -Sy git neovim
      - uses: actions/checkout@v4
        repository: https://github.com/nvim-lua/plenary.nvim
        path: ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
      - uses: actions/checkout@v4
        repository: https://github.com/nvim-treesitter/nvim-treesitter
        path: ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter
      - run: ln -s "$(pwd)" ~/.local/share/nvim/site/pack/vendor/start
      - run: scripts/test
