name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  docs-test:
    steps:
      - uses: actions/checkout@v4
      - name: Setup neovim
        uses: https://github.com/rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}
      - name: Test neovim docs
        run: nvim --headless --noplugin -V1 -es -c "helptags doc"

  stylua:
    steps:
      - uses: actions/checkout@v4
      - name: Run stylua
        uses: https://github.com/JohnnyMorganz/stylua-action@4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .

  luacheck:
    steps:
      - uses: actions/checkout@v4
      - name: Install luacheck
        run: apt-get update -y && apt-get install -y lua-check
      - name: Run luacheck
        run: luacheck .

  test:
    strategy:
      matrix:
        neovim-version: [ 'stable', 'nightly' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup neovim
        uses: https://github.com/rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}
      - name: Checkout plenary
        uses: actions/checkout@v4
        repository: https://github.com/nvim-lua/plenary.nvim
        path: ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
      - name: Checkout treesitter
        uses: actions/checkout@v4
        repository: https://github.com/nvim-treesitter/nvim-treesitter
        path: ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter
      - name: Link plenary and treesitter
        run: ln -s "$(pwd)" ~/.local/share/nvim/site/pack/vendor/start
      - name: Run tests
        run: scripts/test
