#!/bin/sh

if ! type lemmy-help > /dev/null 2>&1
then
	echo "lemmy-help is required to generate docs. Install with `cargo install lemmy-help --features=cli`"
	exit 1
fi

FILES=""
for FILE in $(find lua/devcontainer -name "*.lua" | grep -v "internal")
do
	if [ -f $FILE ]
	then
		FILES="$FILES $FILE"
	fi
done

LINE_NR=$(grep -n "\-\-\-INSERT HERE\-\-\-" scripts/docs-template.txt | cut -f1 -d ':')
head -n $(($LINE_NR - 1)) scripts/docs-template.txt > doc/devcontainer.txt
lemmy-help -M $FILES >> doc/devcontainer.txt
tail --lines=+$(($LINE_NR + 1)) scripts/docs-template.txt >> doc/devcontainer.txt
