local subject = require("devcontainer.internal.executor")

describe("devcontainer.internal.executor:", function()
	describe("given existing executable", function()
		describe("ensure_executable", function()
			it("should not fail", function()
				local success = pcall(subject.ensure_executable, "nvim")
				assert.is_true(success)
			end)
		end)
	end)
	describe("given missing executable", function()
		describe("ensure_executable", function()
			it("should fail", function()
				local success = pcall(subject.ensure_executable, "doker") -- intentional typo
				assert.is_not_true(success)
			end)
		end)
	end)
end)
